-- Create table for Games 2025/2026
create table if not exists games_2025_2026 (
  slug text primary key,
  data date not null,
  hora text,
  equipa_casa text not null,
  equipa_fora text not null,
  resultado_casa integer,
  resultado_fora integer,
  escalao text,
  competicao text,
  local text,
  logotipo_casa text,
  logotipo_fora text,
  status text check (status in ('AGENDADO', 'A DECORRER', 'FINALIZADO')),
  epoca text default '2025/2026',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (Optional, but good practice)
alter table games_2025_2026 enable row level security;
create policy "Public read access" on games_2025_2026 for select using (true);
create policy "Service role full access" on games_2025_2026 using (true);

-- Create table for Standings 2025/2026
create table if not exists classificacoes_2025_2026 (
  id bigint generated by default as identity primary key,
  competicao text not null,
  grupo text not null,
  equipa text not null,
  posicao integer,
  jogos integer,
  vitorias integer,
  derrotas integer,
  pontos integer,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(competicao, grupo, equipa)
);

-- Enable RLS (Optional)
alter table classificacoes_2025_2026 enable row level security;
create policy "Public read access" on classificacoes_2025_2026 for select using (true);
create policy "Service role full access" on classificacoes_2025_2026 using (true);
