-- Migration Script: Switch to Season-Specific Tables

-- 1. Drop old tables (Warning: Data Loss)
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS classificacoes;

-- Also drop current season ones if they exist to ensure clean slate or if they were created by previous testing
DROP TABLE IF EXISTS games_2025_2026;
DROP TABLE IF EXISTS classificacoes_2025_2026;


-- 2. Create Games Tables for all seasons
-- 2022/2023
CREATE TABLE IF NOT EXISTS games_2022_2023 (
  slug text primary key,
  data date not null,
  hora text,
  equipa_casa text not null,
  equipa_fora text not null,
  resultado_casa integer,
  resultado_fora integer,
  escalao text,
  competicao text,
  local text,
  logotipo_casa text,
  logotipo_fora text,
  status text check (status in ('AGENDADO', 'A DECORRER', 'FINALIZADO')),
  epoca text default '2022/2023',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE games_2022_2023 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON games_2022_2023 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON games_2022_2023 USING (true);

-- 2023/2024
CREATE TABLE IF NOT EXISTS games_2023_2024 (
  slug text primary key,
  data date not null,
  hora text,
  equipa_casa text not null,
  equipa_fora text not null,
  resultado_casa integer,
  resultado_fora integer,
  escalao text,
  competicao text,
  local text,
  logotipo_casa text,
  logotipo_fora text,
  status text check (status in ('AGENDADO', 'A DECORRER', 'FINALIZADO')),
  epoca text default '2023/2024',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE games_2023_2024 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON games_2023_2024 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON games_2023_2024 USING (true);

-- 2024/2025
CREATE TABLE IF NOT EXISTS games_2024_2025 (
  slug text primary key,
  data date not null,
  hora text,
  equipa_casa text not null,
  equipa_fora text not null,
  resultado_casa integer,
  resultado_fora integer,
  escalao text,
  competicao text,
  local text,
  logotipo_casa text,
  logotipo_fora text,
  status text check (status in ('AGENDADO', 'A DECORRER', 'FINALIZADO')),
  epoca text default '2024/2025',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE games_2024_2025 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON games_2024_2025 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON games_2024_2025 USING (true);

-- 2025/2026 (Current)
CREATE TABLE IF NOT EXISTS games_2025_2026 (
  slug text primary key,
  data date not null,
  hora text,
  equipa_casa text not null,
  equipa_fora text not null,
  resultado_casa integer,
  resultado_fora integer,
  escalao text,
  competicao text,
  local text,
  logotipo_casa text,
  logotipo_fora text,
  status text check (status in ('AGENDADO', 'A DECORRER', 'FINALIZADO')),
  epoca text default '2025/2026',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE games_2025_2026 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON games_2025_2026 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON games_2025_2026 USING (true);


-- 3. Create Standings Tables for all seasons
-- 2022/2023
CREATE TABLE IF NOT EXISTS classificacoes_2022_2023 (
  id bigint generated by default as identity primary key,
  competicao text not null,
  grupo text not null,
  equipa text not null,
  posicao integer,
  jogos integer,
  vitorias integer,
  derrotas integer,
  pontos integer,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(competicao, grupo, equipa)
);
ALTER TABLE classificacoes_2022_2023 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON classificacoes_2022_2023 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON classificacoes_2022_2023 USING (true);

-- 2023/2024
CREATE TABLE IF NOT EXISTS classificacoes_2023_2024 (
  id bigint generated by default as identity primary key,
  competicao text not null,
  grupo text not null,
  equipa text not null,
  posicao integer,
  jogos integer,
  vitorias integer,
  derrotas integer,
  pontos integer,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(competicao, grupo, equipa)
);
ALTER TABLE classificacoes_2023_2024 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON classificacoes_2023_2024 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON classificacoes_2023_2024 USING (true);

-- 2024/2025
CREATE TABLE IF NOT EXISTS classificacoes_2024_2025 (
  id bigint generated by default as identity primary key,
  competicao text not null,
  grupo text not null,
  equipa text not null,
  posicao integer,
  jogos integer,
  vitorias integer,
  derrotas integer,
  pontos integer,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(competicao, grupo, equipa)
);
ALTER TABLE classificacoes_2024_2025 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON classificacoes_2024_2025 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON classificacoes_2024_2025 USING (true);

-- 2025/2026 (Current)
CREATE TABLE IF NOT EXISTS classificacoes_2025_2026 (
  id bigint generated by default as identity primary key,
  competicao text not null,
  grupo text not null,
  equipa text not null,
  posicao integer,
  jogos integer,
  vitorias integer,
  derrotas integer,
  pontos integer,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(competicao, grupo, equipa)
);
ALTER TABLE classificacoes_2025_2026 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON classificacoes_2025_2026 FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON classificacoes_2025_2026 USING (true);
