-- Tabela para gestão de clubes e competições seguidos pelos utilizadores
CREATE TABLE IF NOT EXISTS user_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('club', 'competition')),
    entity_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, entity_type, entity_id)
);

-- Row Level Security
ALTER TABLE user_follows ENABLE ROW LEVEL SECURITY;

-- Utilizadores podem ler os seus próprios follows
CREATE POLICY "Users read own follows" ON user_follows
    FOR SELECT USING (auth.uid() = user_id);

-- Utilizadores podem inserir os seus próprios follows
CREATE POLICY "Users insert own follows" ON user_follows
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Utilizadores podem remover os seus próprios follows
CREATE POLICY "Users delete own follows" ON user_follows
    FOR DELETE USING (auth.uid() = user_id);

-- Index para consultas por utilizador
CREATE INDEX IF NOT EXISTS idx_user_follows_user ON user_follows(user_id, entity_type);
